language: php
git:
  depth: 1
php:
  - 8.3
before_script:
  - phpenv config-rm xdebug.ini
  - composer install -v
script:
  - vendor/bin/phpunit -c phpunit.xml.dist --testsuite 'Year 2020'
  - vendor/bin/phpunit -c phpunit.xml.dist --testsuite 'Year 2023'
jobs:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache
