language: php
git:
    depth: 1
php:
    - 7.4
    - 8.0
    - nightly
before_script:
    - phpenv config-rm xdebug.ini
    - composer install -v
script:
    - vendor/bin/phpunit -v tests/
jobs:
    fast_finish: true
    allow_failures:
        - php: nightly

cache:
    directories:
        - $HOME/.composer/cache
