language: php
git:
  depth: 1
php:
  - 8.3
before_script:
  - phpenv config-rm xdebug.ini
  - composer install -v
script:
  - vendor/bin/phpunit -v tests/
jobs:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache
